In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

%matplotlib inline

In [2]:
df_final_demo = pd.read_csv("df_final_demo.txt")
df_exp_cli = pd.read_csv("df_final_experiment_clients.txt")
df_web_1 = pd.read_csv("df_final_web_data_pt_1.txt")
df_web_2 = pd.read_csv("df_final_web_data_pt_2.txt")

In [58]:
df_web_2.isnull().sum()/df_web_2.shape[0]

client_id       0.0
visitor_id      0.0
visit_id        0.0
process_step    0.0
date_time       0.0
dtype: float64

In [3]:
df_final_demo.head()

client_id  clnt_tenure_yr  clnt_tenure_mnth  clnt_age gendr  num_accts  \
0     836976             6.0              73.0      60.5     U        2.0   
1    2304905             7.0              94.0      58.0     U        2.0   
2    1439522             5.0              64.0      32.0     U        2.0   
3    1562045            16.0             198.0      49.0     M        2.0   
4    5126305            12.0             145.0      33.0     F        2.0   

         bal  calls_6_mnth  logons_6_mnth  
0   45105.30           6.0            9.0  
1  110860.30           6.0            9.0  
2   52467.79           6.0            9.0  
3   67454.65           3.0            6.0  
4  103671.75           0.0            3.0

In [4]:
df_exp_cli.head()

client_id Variation
0    9988021      Test
1    8320017      Test
2    4033851   Control
3    1982004      Test
4    9294070   Control

In [5]:
df_web_1.head()

client_id            visitor_id                      visit_id process_step  \
0    9988021  580560515_7732621733  781255054_21935453173_531117       step_3   
1    9988021  580560515_7732621733  781255054_21935453173_531117       step_2   
2    9988021  580560515_7732621733  781255054_21935453173_531117       step_3   
3    9988021  580560515_7732621733  781255054_21935453173_531117       step_2   
4    9988021  580560515_7732621733  781255054_21935453173_531117       step_3   

             date_time  
0  2017-04-17 15:27:07  
1  2017-04-17 15:26:51  
2  2017-04-17 15:19:22  
3  2017-04-17 15:19:13  
4  2017-04-17 15:18:04

In [6]:
df_web_2.head()

client_id             visitor_id                      visit_id  \
0     763412  601952081_10457207388  397475557_40440946728_419634   
1    6019349  442094451_91531546617  154620534_35331068705_522317   
2    6019349  442094451_91531546617  154620534_35331068705_522317   
3    6019349  442094451_91531546617  154620534_35331068705_522317   
4    6019349  442094451_91531546617  154620534_35331068705_522317   

  process_step            date_time  
0      confirm  2017-06-06 08:56:00  
1      confirm  2017-06-01 11:59:27  
2       step_3  2017-06-01 11:58:48  
3       step_2  2017-06-01 11:58:08  
4       step_1  2017-06-01 11:57:58

In [7]:
df_web = pd.concat([df_web_1, df_web_2], axis=0)
df_web.head()

client_id            visitor_id                      visit_id process_step  \
0    9988021  580560515_7732621733  781255054_21935453173_531117       step_3   
1    9988021  580560515_7732621733  781255054_21935453173_531117       step_2   
2    9988021  580560515_7732621733  781255054_21935453173_531117       step_3   
3    9988021  580560515_7732621733  781255054_21935453173_531117       step_2   
4    9988021  580560515_7732621733  781255054_21935453173_531117       step_3   

             date_time  
0  2017-04-17 15:27:07  
1  2017-04-17 15:26:51  
2  2017-04-17 15:19:22  
3  2017-04-17 15:19:13  
4  2017-04-17 15:18:04

In [8]:
df = pd.merge(df_web, df_exp_cli, on ='client_id',how='outer')
df.head()

client_id             visitor_id                      visit_id  \
0        169  201385055_71273495308  749567106_99161211863_557568   
1        169  201385055_71273495308  749567106_99161211863_557568   
2        169  201385055_71273495308  749567106_99161211863_557568   
3        169  201385055_71273495308  749567106_99161211863_557568   
4        169  201385055_71273495308  749567106_99161211863_557568   

  process_step            date_time Variation  
0      confirm  2017-04-12 20:23:09       NaN  
1       step_3  2017-04-12 20:22:05       NaN  
2       step_2  2017-04-12 20:20:31       NaN  
3       step_1  2017-04-12 20:19:45       NaN  
4        start  2017-04-12 20:19:36       NaN

In [9]:
df = pd.merge(df, df_final_demo, on ='client_id',how='outer')

In [36]:
df.head()

client_id             visitor_id                      visit_id  \
0        169  201385055_71273495308  749567106_99161211863_557568   
1        169  201385055_71273495308  749567106_99161211863_557568   
2        169  201385055_71273495308  749567106_99161211863_557568   
3        169  201385055_71273495308  749567106_99161211863_557568   
4        169  201385055_71273495308  749567106_99161211863_557568   

  process_step           date_time variation  clnt_tenure_yr  \
0      confirm 2017-04-12 20:23:09       NaN              21   
1       step_3 2017-04-12 20:22:05       NaN              21   
2       step_2 2017-04-12 20:20:31       NaN              21   
3       step_1 2017-04-12 20:19:45       NaN              21   
4        start 2017-04-12 20:19:36       NaN              21   

   clnt_tenure_mnth  clnt_age gendr  num_accts        bal  calls_6_mnth  \
0               262      47.5     M          2  501570.72             4   
1               262      47.5     M          2  501570.72             4   
2               262      47.5     M          2  501570.72             4   
3               262      47.5     M          2  501570.72             4   
4               262      47.5     M          2  501570.72             4   

   logons_6_mnth  
0              4  
1              4  
2              4  
3              4  
4              4

In [11]:
df.shape

(755405, 14)

In [12]:
df.dtypes

client_id             int64
visitor_id           object
visit_id             object
process_step         object
date_time            object
Variation            object
clnt_tenure_yr      float64
clnt_tenure_mnth    float64
clnt_age            float64
gendr                object
num_accts           float64
bal                 float64
calls_6_mnth        float64
logons_6_mnth       float64
dtype: object

In [13]:
df['date_time'] = pd.to_datetime(df['date_time'], errors='coerce')

In [14]:
df['date_time'].isna().sum()

0

In [23]:
df['clnt_tenure_yr'].unique()

<IntegerArray>
[  21, <NA>,    3,   12,   11,    9,    5,    8,    7,   48,   14,   19,   23,
   13,    4,   15,    6,   16,   30,   27,   18,   20,   22,   17,   10,   24,
   26,   25,   28,   29,   43,   32,   31,   34,   36,   55,   33,   35,    2,
   51,   37,   38,   62,   40,   45,   39,   50,   52,   47,   44,   42,   41,
   46,   54,   49]
Length: 55, dtype: Int64

In [52]:
np.sort(df['clnt_tenure_yr'].unique())

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,
       28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40.,
       41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52., 54.,
       55., 62., nan])

In [51]:
df['clnt_tenure_yr'].unique()

<IntegerArray>
[  21, <NA>,    3,   12,   11,    9,    5,    8,    7,   48,   14,   19,   23,
   13,    4,   15,    6,   16,   30,   27,   18,   20,   22,   17,   10,   24,
   26,   25,   28,   29,   43,   32,   31,   34,   36,   55,   33,   35,    2,
   51,   37,   38,   62,   40,   45,   39,   50,   52,   47,   44,   42,   41,
   46,   54,   49]
Length: 55, dtype: Int64

In [ ]:
df['clnt_age'].unique()

array([47.5,  nan, 29.5, 57.5, 59.5, 51. , 36. , 48. , 22. , 54.5, 28.5,
       42. , 46. , 45. , 58.5, 51.5, 55. , 43. , 62.5, 46.5, 37.5, 26.5,
       63.5, 56. , 25. , 52. , 63. , 30. , 70.5, 48.5, 38.5, 58. , 40. ,
       65.5, 64.5, 50.5, 40.5, 29. , 76. , 25.5, 67. , 35.5, 53. , 61.5,
       41.5, 33. , 44. , 50. , 30.5, 55.5, 34. , 27. , 22.5, 38. , 36.5,
       82. , 26. , 74. , 23. , 31.5, 60. , 53.5, 28. , 37. , 39. , 27.5,
       77.5, 52.5, 19.5, 62. , 34.5, 69. , 54. , 45.5, 65. , 21. , 20. ,
       60.5, 74.5, 68. , 61. , 41. , 43.5, 75.5, 49.5, 32. , 67.5, 19. ,
       49. , 23.5, 33.5, 24. , 76.5, 71. , 59. , 15.5, 69.5, 56.5, 66. ,
       32.5, 42.5, 57. , 47. , 81.5, 31. , 44.5, 71.5, 70. , 24.5, 75. ,
       77. , 81. , 14.5, 86.5, 73. , 39.5, 73.5, 79.5, 21.5, 85. , 35. ,
       80. , 72.5, 78. , 18.5, 64. , 68.5, 66.5, 84. , 72. , 20.5, 83. ,
       91. , 83.5, 16.5, 18. , 95.5, 82.5, 16. , 17. , 17.5, 80.5, 84.5,
       78.5, 92. , 79. , 89. , 15. , 90. , 86. , 87

In [49]:
np.sort(df['clnt_age'].unique())

array([13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5,
       19. , 19.5, 20. , 20.5, 21. , 21.5, 22. , 22.5, 23. , 23.5, 24. ,
       24.5, 25. , 25.5, 26. , 26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5,
       30. , 30.5, 31. , 31.5, 32. , 32.5, 33. , 33.5, 34. , 34.5, 35. ,
       35.5, 36. , 36.5, 37. , 37.5, 38. , 38.5, 39. , 39.5, 40. , 40.5,
       41. , 41.5, 42. , 42.5, 43. , 43.5, 44. , 44.5, 45. , 45.5, 46. ,
       46.5, 47. , 47.5, 48. , 48.5, 49. , 49.5, 50. , 50.5, 51. , 51.5,
       52. , 52.5, 53. , 53.5, 54. , 54.5, 55. , 55.5, 56. , 56.5, 57. ,
       57.5, 58. , 58.5, 59. , 59.5, 60. , 60.5, 61. , 61.5, 62. , 62.5,
       63. , 63.5, 64. , 64.5, 65. , 65.5, 66. , 66.5, 67. , 67.5, 68. ,
       68.5, 69. , 69.5, 70. , 70.5, 71. , 71.5, 72. , 72.5, 73. , 73.5,
       74. , 74.5, 75. , 75.5, 76. , 76.5, 77. , 77.5, 78. , 78.5, 79. ,
       79.5, 80. , 80.5, 81. , 81.5, 82. , 82.5, 83. , 83.5, 84. , 84.5,
       85. , 85.5, 86. , 86.5, 87. , 87.5, 88. , 88

In [21]:
df['clnt_tenure_yr'] = df['clnt_tenure_yr'].astype('Int64')

In [22]:
df['clnt_tenure_mnth'] = df['clnt_tenure_mnth'].astype('Int64')

In [28]:
df['num_accts'].unique()

<IntegerArray>
[2, <NA>, 3, 5, 4, 6, 8, 7, 1]
Length: 9, dtype: Int64

In [27]:
df['num_accts'] = df['num_accts'].astype('Int64')

In [32]:
df['calls_6_mnth'].unique()

<IntegerArray>
[4, <NA>, 2, 0, 1, 6, 5, 3, 7]
Length: 9, dtype: Int64

In [31]:
df['calls_6_mnth'] = df['calls_6_mnth'].astype('Int64')

In [34]:
df['logons_6_mnth'].unique()

<IntegerArray>
[4, <NA>, 6, 1, 3, 9, 5, 8, 7, 2]
Length: 10, dtype: Int64

In [33]:
df['logons_6_mnth'] = df['logons_6_mnth'].astype('Int64')

In [35]:
df.columns = df.columns.str.lower()

In [44]:
df['gendr'].unique()

array(['M', 'U', 'F', 'X'], dtype=object)

In [41]:
df.duplicated().sum()

0

In [40]:
df = df.drop_duplicates()

In [43]:
df['gendr'] = df['gendr'].fillna('U')

In [45]:
df.isnull().sum()

client_id                0
visitor_id               0
visit_id                 0
process_step             0
date_time                0
variation           427406
clnt_tenure_yr      300857
clnt_tenure_mnth    300857
clnt_age            300869
gendr                    0
num_accts           300857
bal                 300857
calls_6_mnth        300857
logons_6_mnth       300857
dtype: int64

In [46]:
df.isnull().sum()/df.shape[0]

client_id           0.000000
visitor_id          0.000000
visit_id            0.000000
process_step        0.000000
date_time           0.000000
variation           0.573976
clnt_tenure_yr      0.404030
clnt_tenure_mnth    0.404030
clnt_age            0.404046
gendr               0.000000
num_accts           0.404030
bal                 0.404030
calls_6_mnth        0.404030
logons_6_mnth       0.404030
dtype: float64

In [ ]:
# df.to_csv('df_final.csv', index=False)